### PR TITLE
seattle gentx

### PR DESCRIPTION
**Pull request by mchaker**
running towards the longsword as the pillar of autumn goes critical

### CODE REVIEW

**Comment by jkilpatr** [comment]
this gentx isn't valid.

**Comment by mchaker** [comment]
@jkilpatr I followed the gentx instructions with the flag `--chain-id=gravity-bridge-test1`

**Comment by mchaker** [comment]
found the issue, tried again in #133

**Comment by mchaker** [comment]
fixed in #133

**Pull request closed without merging**
